# -*- coding: utf-8 -*-
"""grundy9monedas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1onJwYbcQ7dR429bA8M7XpLs2Q4q5nqMP
"""

import networkx as nx
import matplotlib.pyplot as plt

def calcular_grundy(conjuntos, grafo, nodo_padre=None):
    # Convertimos a tupla ordenada para usarla como identificador único de nodo
    estado_actual = tuple(sorted(conjuntos, reverse=True))

    # Añadir el nodo al grafo si no existe
    grafo.add_node(estado_actual)

    if nodo_padre:
        grafo.add_edge(nodo_padre, estado_actual)

    # Filtrar montones divisibles (impares mayores que 2)
    divisibles = [x for x in conjuntos if x % 2 != 0 and x > 2]

    for c in divisibles:
        for i in range(1, (c // 2) + 1):
            j = c - i
            if i != j:
                nuevos_conjuntos = list(conjuntos)
                nuevos_conjuntos.remove(c)
                nuevos_conjuntos.extend([i, j])

                # Llamada recursiva para armar la siguiente rama
                calcular_grundy(nuevos_conjuntos, grafo, estado_actual)

# 1. Crear el grafo dirigido
G = nx.DiGraph()
calcular_grundy([9], G)

# 2. Configurar el diseño visual (Layout Jerárquico)
plt.figure(figsize=(14, 8))
plt.title("Árbol de Espacio de Estados - Juego de Grundy (9 monedas)", fontsize=14)

# Intentar usar diseño de árbol (requiere pydot), si no, usa el diseño por capas de networkx
try:
    pos = nx.drawing.nx_pydot.graphviz_layout(G, prog='dot')
except:
    pos = nx.spring_layout(G, seed=42) # Alternativa por si no tienes Graphviz

# 3. Dibujar los componentes
nx.draw_networkx_nodes(G, pos, node_size=1200, node_color='#bbf', edgecolors='#333')
nx.draw_networkx_edges(G, pos, arrowstyle='->', arrowsize=15, edge_color='gray')

# Formatear las etiquetas para que se vean como listas [9], [7, 2], etc.
labels = {nodo: str(list(nodo)) for nodo in G.nodes()}
nx.draw_networkx_labels(G, pos, labels=labels, font_size=8, font_weight='bold')

plt.axis('off')
plt.tight_layout()
plt.show()