# -*- coding: utf-8 -*-
"""Extractor_PDF_Portafolio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bEue6ybj10sCR1JIV9MOukPvG4ZQBw83

# 📸 Extractor de screenshots para el portafolio de Ciberseguridad

Este notebook extrae automáticamente las capturas de pantalla de tus informes PDF,
filtrando logos y elementos decorativos, para que puedas armar el README de cada
proyecto sin transcribir nada a mano.

**Flujo:** instalar dependencias → escribir el script → subir tu(s) PDF(s) → ejecutar → descargar el resultado (`screenshots/`).

## 1. Instalar dependencias (poppler-utils)
"""

!apt-get update && apt-get install -y poppler-utils -qq

"""## 2. Escribir el script `extract_pdf_to_project.py`
(Solo corre esta celda una vez por sesión, no hace falta subir el .py aparte).
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile extract_pdf_to_project.py
# #!/usr/bin/env python3
# """
# Extrae imágenes de un informe PDF hacia una carpeta especificada,
# filtrando logos o elementos pequeños.
#
# Uso:
#     python3 extract_pdf_to_project.py <ruta_pdf> <carpeta_salida> [--min-width 300]
#
# Genera:
#     <carpeta_salida>/01_pagina1.png, 02_pagina1.png, ...
# """
#
# import subprocess
# import sys
# import os
# import argparse
# import shutil
# import tempfile
#
#
# def run(cmd):
#     result = subprocess.run(cmd, capture_output=True, text=True)
#     if result.returncode != 0:
#         print(f"⚠️  Error ejecutando: {' '.join(cmd)}\n{result.stderr}", file=sys.stderr)
#     return result.stdout
#
#
# def parse_pdfimages_list(pdf_path):
#     """Devuelve lista de dicts con información de cada imagen embebida."""
#     output = run(["pdfimages", "-list", pdf_path])
#     lines = output.strip().split("\n")
#     images = []
#     for line in lines[2:]:  # Saltado de encabezado
#         parts = line.split()
#         if len(parts) < 8:
#             continue
#         try:
#             images.append({
#                 "page": int(parts[0]),
#                 "num": int(parts[1]),
#                 "width": int(parts[3]),
#                 "height": int(parts[4]),
#             })
#         except (ValueError, IndexError):
#             continue
#     return images
#
#
# def extract_images(pdf_path, out_dir, min_width, min_height):
#     os.makedirs(out_dir, exist_ok=True)
#     images_meta = parse_pdfimages_list(pdf_path)
#
#     with tempfile.TemporaryDirectory() as tmp:
#         prefix = os.path.join(tmp, "img")
#         run(["pdfimages", "-png", pdf_path, prefix])
#
#         extracted = sorted(os.listdir(tmp))
#         kept = []
#         counter = 1
#         pad_width = max(2, len(str(len(extracted))))
#
#         for i, fname in enumerate(extracted):
#             full_path = os.path.join(tmp, fname)
#             try:
#                 size = os.path.getsize(full_path)
#             except OSError:
#                 continue
#
#             # Filtrar por dimensiones usando la metadata de pdfimages -list
#             meta = images_meta[i] if i < len(images_meta) else None
#             width = meta["width"] if meta else None
#             height = meta["height"] if meta else None
#
#             if width is not None and width < min_width:
#                 continue
#             if height is not None and height < min_height:
#                 continue
#             if size < 3000:  # Descarta imágenes vacías o máscaras diminutas
#                 continue
#
#             page = meta["page"] if meta else "?"
#             new_name = f"{counter:0{pad_width}d}_pagina{page}.png"
#             shutil.copy(full_path, os.path.join(out_dir, new_name))
#             kept.append(new_name)
#             counter += 1
#
#     return kept
#
#
# def main():
#     parser = argparse.ArgumentParser(description="Extrae y filtra las imágenes de un archivo PDF.")
#     parser.add_argument("pdf_path", help="Ruta al archivo PDF")
#     parser.add_argument("output_dir", help="Carpeta de destino para guardar las imágenes")
#     parser.add_argument("--min-width", type=int, default=300, help="Ancho mínimo en px para conservar la imagen (default: 300)")
#     parser.add_argument("--min-height", type=int, default=150, help="Alto mínimo en px para conservar la imagen (default: 150)")
#     args = parser.parse_args()
#
#     print(f"📄 Procesando: {args.pdf_path}")
#     kept = extract_images(args.pdf_path, args.output_dir, args.min_width, args.min_height)
#     print(f"🖼️  Imágenes extraídas y guardadas: {len(kept)} → {args.output_dir}")
#     print("\n✅ Listo.")
#
#
# if __name__ == "__main__":
#     main()
#

"""## 3. Subir tu PDF (o varios)
Se abrirá un diálogo para seleccionar archivo(s) desde tu computadora.
"""

from google.colab import files
uploaded = files.upload()
print('Archivos subidos:', list(uploaded.keys()))

"""## 4. Procesar UN PDF

Cambia `mi_informe.pdf` por el nombre real del archivo que subiste, y `NombreDelProyecto` por el nombre de la carpeta del proyecto en tu repo.
"""

pdf_path = "IAAC_PF_T6.pdf"        # <-- cambia esto
carpeta_proyecto = "p7"  # <-- cambia esto

!python3 extract_pdf_to_project.py "{pdf_path}" "./{carpeta_proyecto}"

"""### (Opcional) Procesar VARIOS PDFs de una vez

Si subiste varios informes en el paso 3, edita el diccionario de abajo: `"archivo.pdf": "NombreCarpeta"` y corre la celda en lugar de la anterior.
"""

import os

pdfs = {
    # "informe1.pdf": "Proyecto-1",
    # "informe2.pdf": "Proyecto-2",
}

for pdf, carpeta in pdfs.items():
    print(f"\n=== Procesando {pdf} -> {carpeta} ===")
    os.system(f'python3 extract_pdf_to_project.py "{pdf}" "./{carpeta}"')

"""## 5. Revisar el resultado"""

!ls -la "{carpeta_proyecto}/screenshots" | head -30

"""## 6. Descargar la carpeta del proyecto (comprimida)

Colab no permite descargar carpetas directamente, así que la comprimimos primero.
"""

import shutil
from google.colab import files

zip_name = f"{carpeta_proyecto}.zip"
shutil.make_archive(carpeta_proyecto, 'zip', carpeta_proyecto)
files.download(zip_name)

"""---
### Notas
- Si el filtro por defecto (`--min-width 300 --min-height 150`) deja pasar basura o corta capturas válidas, ajústalo así:
  ```python
  !python3 extract_pdf_to_project.py "mi_informe.pdf" "./Proyecto" --min-width 400 --min-height 200
  ```
- El script **no sanitiza** IPs, nombres o credenciales — eso sigue siendo revisión manual tuya antes de subir a GitHub.
"""